[tool.briefcase]
project_name = 'Wormhole'
bundle = 'com.pavelsof'
version = '0.3.0'

url = 'https://github.com/pavelsof/mobile-wormhole'
author = 'pavelsof'
author_email = 'mail@pavelsof.com'


[tool.briefcase.app.mobile_wormhole]
formal_name = 'Wormhole'
description = "Send and receive files using the Magic Wormhole protocol"

icon = 'src/img/icon'
splash = 'src/img/splash'

sources = ['mobile_wormhole']
requires = [
    'magic-wormhole==0.12.0',
]


[tool.briefcase.app.mobile_wormhole.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.mobile_wormhole.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.mobile_wormhole.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.mobile_wormhole.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.mobile_wormhole.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

[tool.briefcase.app.mobile_wormhole.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.mobile_wormhole.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.mobile_wormhole.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
